CREATE TABLE users (
id SERIAL PRIMARY KEY NOT NULL,
username VARCHAR (90) NOT NULL,
first_name VARCHAR (90) DEFAULT NULL,
last_name VARCHAR (90) DEFAULT NULL,
created_at TIMESTAMP WITH time zone NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP WITH time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE posts (
id SERIAL PRIMARY KEY NOT NULL,
title VARCHAR (180) DEFAULT NULL,
url VARCHAR (510) DEFAULT NULL,
content text DEFAULT NULL,
created_at TIMESTAMP WITH time zone NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP WITH time zone NOT NULL DEFAULT NOW()
);